services:
  adminer-mariadb-10.5:
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on:
          - mysql-mariadb-10.5

  mysql-mariadb-10.5:
    image: mariadb:10.5
    # image: mysql:8.0 # 囲み文字を使用する場合
    volumes:
        - mysql-db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: xiao
        MYSQL_USER: xiao
        MYSQL_PASSWORD: xiao
        TZ: "Asia/Tokyo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
    restart: always
    logging:
        options:
            max-size: "10m"
            max-file: "3"

volumes:
    mysql-db:
